linters:
  checkstyle:
    config: ./checkstyle.xml
  eslint:
    config: './eslint.config'
  csslint:
review:
  # Don't use 'failure' build status when
  # a pull request contains style errors.
  fail_on_comments: false
